import {
  Activity, AlarmClock, Ambulance, Anchor, AppWindow, Apple,
  Archive, Armchair, Atom, AtSign, Baby, Backpack,
  Banana, Bandage, Banknote, Bath, Battery, Bed,
  Beef, Beer, Bell, Bike, Binary, Bird,
  Bone, Book, Bookmark, BookOpen, Bot, Box,
  Boxes, Braces, Brain, Briefcase, Brush, Bug,
  Building, Building2, Bus, Cake, CakeSlice, Calculator,
  Calendar, Camera, Car, Carrot, Castle, Cat,
  CheckCircle2, CheckSquare, Church, CircuitBoard, Circle, Clapperboard,
  Clipboard, ClipboardCheck, Clock, Cloud, CloudRain, CloudSun,
  Code, Coffee, Coins, Compass, Construction, Cookie,
  Cpu, CreditCard, Cross, Crown, CupSoda, Database,
  Dice5, Disc, Dog, DoorOpen, Drama, Drill,
  Droplet, Drum, Dumbbell, Egg, Eye, Feather,
  FerrisWheel, FileCode, FileText, Film, Filter, Fingerprint,
  Fish, Flag, Flame, Flashlight, FlaskConical, Flower,
  Flower2, Folder, Footprints, Frame, Fuel, Gamepad2,
  Gauge, Gem, Ghost, Gift, GitBranch, Glasses,
  Globe, GraduationCap, Grid3x3, Guitar, Hammer, Handshake,
  HardDrive, HardHat, Headphones, Heart, HeartHandshake, HeartPulse,
  Hexagon, Home, Hourglass, House, IceCreamCone, Image,
  Inbox, Infinity as InfinityIcon, Kanban, Key, Keyboard, KeyRound,
  Lamp, Landmark, Laptop, Layers, LayoutDashboard, LayoutGrid, Leaf,
  Library, LifeBuoy, Lightbulb, LineChart, Link, List,
  ListTodo, Lock, Luggage, Mail, Map, MapPin,
  MapPinned, Medal, MessageCircle, Mic, Microscope, Monitor,
  Moon, MoonStar, Mountain, Mouse, MousePointer2, Music,
  Music2, Music4, Navigation, Network, Newspaper, Notebook,
  Orbit, Package, Paintbrush, PaintRoller, Palette, Palmtree,
  PanelsTopLeft, PartyPopper, PawPrint, Pen, Pencil, PenTool,
  Phone, PhoneCall, Piano, PieChart, PiggyBank, Pill,
  Pin, Pizza, Plane, Plug, Plug2, Presentation,
  Printer, Puzzle, Rabbit, Radio, Receipt, Recycle,
  Rocket, Route, Router, Ruler, Sailboat, Sandwich,
  Satellite, School, Scissors, Search, Send, Server,
  Settings, Share2, Shield, ShieldCheck, Ship, Shirt,
  ShoppingBag, ShoppingCart, ShowerHead, Signpost, Siren, Skull,
  SlidersHorizontal, Smartphone, Smile, Snail, Snowflake, Sofa,
  Soup, Sparkle, Sparkles, Sprout, Square, Squirrel,
  Star, Stethoscope, StickyNote, Store, Sun, Syringe,
  Tablet, Tag, Target, Telescope, Tent, Terminal,
  Thermometer, ThermometerSun, Ticket, ToggleLeft, TrafficCone, TrainFront,
  TreePine, Trees, TrendingUp, Triangle, Trophy, Truck,
  Turtle, Tv, Umbrella, User, UserRound, Users,
  Utensils, UtensilsCrossed, Video, Wallet, Wallet2, Warehouse,
  Watch, Waves, Wifi, Wine, Wrench, Zap,
  type LucideIcon,
} from 'lucide-react';
// A second batch, added after feedback that the first one still had real
// gaps — people, legal/admin, home appliances, food, events, sports.
import {
  Award, CalendarHeart, Candy, ChefHat, ClipboardList, Contact,
  Factory, FileSignature, Gavel, Martini, PaintBucket, PersonStanding,
  Podcast, Popcorn, Refrigerator, Salad, Scale, ShoppingBasket,
  Signature, Speaker, SprayCan, Swords, IdCard, Users2,
  Vault, Volleyball, Vote, WashingMachine,
} from 'lucide-react';

/**
 * A curated set of themes a project actually tends to be about, rather than
 * the app's own closed, hand-drawn set of ~45 chrome glyphs (see Icon.tsx) —
 * those are built for buttons and menus, not for telling a "Travel" project
 * apart from a "Health" one at a glance. Kept in its own file since importing
 * this many names is the whole content of it.
 */
export const PROJECT_ICONS: Record<string, LucideIcon> = {
  'activity': Activity,
  'alarm-clock': AlarmClock,
  'ambulance': Ambulance,
  'anchor': Anchor,
  'apple': Apple,
  'archive': Archive,
  'armchair': Armchair,
  'at-sign': AtSign,
  'atom': Atom,
  'baby': Baby,
  'backpack': Backpack,
  'banana': Banana,
  'bandage': Bandage,
  'banknote': Banknote,
  'bath': Bath,
  'battery': Battery,
  'bed': Bed,
  'beef': Beef,
  'beer': Beer,
  'bell': Bell,
  'bike': Bike,
  'bird': Bird,
  'bone': Bone,
  'book': Book,
  'book-open': BookOpen,
  'bookmark': Bookmark,
  'box': Box,
  'boxes': Boxes,
  'brain': Brain,
  'briefcase': Briefcase,
  'brush': Brush,
  'bug': Bug,
  'building': Building,
  'building-2': Building2,
  'bus': Bus,
  'cake': Cake,
  'cake-slice': CakeSlice,
  'calculator': Calculator,
  'calendar': Calendar,
  'camera': Camera,
  'car': Car,
  'carrot': Carrot,
  'castle': Castle,
  'cat': Cat,
  'check-circle-2': CheckCircle2,
  'church': Church,
  'circle': Circle,
  'clapperboard': Clapperboard,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'clock': Clock,
  'cloud': Cloud,
  'cloud-rain': CloudRain,
  'cloud-sun': CloudSun,
  'code': Code,
  'coffee': Coffee,
  'coins': Coins,
  'compass': Compass,
  'construction': Construction,
  'cookie': Cookie,
  'cpu': Cpu,
  'credit-card': CreditCard,
  'cross': Cross,
  'crown': Crown,
  'cup-soda': CupSoda,
  'database': Database,
  'dice-5': Dice5,
  'disc': Disc,
  'dog': Dog,
  'door-open': DoorOpen,
  'drama': Drama,
  'drill': Drill,
  'droplet': Droplet,
  'drum': Drum,
  'dumbbell': Dumbbell,
  'egg': Egg,
  'eye': Eye,
  'feather': Feather,
  'ferris-wheel': FerrisWheel,
  'file-text': FileText,
  'film': Film,
  'filter': Filter,
  'fingerprint': Fingerprint,
  'fish': Fish,
  'flag': Flag,
  'flame': Flame,
  'flashlight': Flashlight,
  'flask-conical': FlaskConical,
  'flower': Flower,
  'flower-2': Flower2,
  'folder': Folder,
  'footprints': Footprints,
  'frame': Frame,
  'fuel': Fuel,
  'gamepad': Gamepad2,
  'gem': Gem,
  'ghost': Ghost,
  'gift': Gift,
  'git-branch': GitBranch,
  'glasses': Glasses,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'grid-3x3': Grid3x3,
  'guitar': Guitar,
  'hammer': Hammer,
  'handshake': Handshake,
  'hard-hat': HardHat,
  'headphones': Headphones,
  'heart': Heart,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  'hexagon': Hexagon,
  'home': Home,
  'hourglass': Hourglass,
  'house': House,
  'ice-cream-cone': IceCreamCone,
  'image': Image,
  'inbox': Inbox,
  'infinity': InfinityIcon,
  'key': Key,
  'key-round': KeyRound,
  'keyboard': Keyboard,
  'lamp': Lamp,
  'landmark': Landmark,
  'laptop': Laptop,
  'layers': Layers,
  'leaf': Leaf,
  'library': Library,
  'life-buoy': LifeBuoy,
  'lightbulb': Lightbulb,
  'line-chart': LineChart,
  'link': Link,
  'list': List,
  'lock': Lock,
  'luggage': Luggage,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  'medal': Medal,
  'message-circle': MessageCircle,
  'mic': Mic,
  'microscope': Microscope,
  'monitor': Monitor,
  'moon': Moon,
  'moon-star': MoonStar,
  'mountain': Mountain,
  'mouse': Mouse,
  'music': Music,
  'music-2': Music2,
  'music-4': Music4,
  'navigation': Navigation,
  'newspaper': Newspaper,
  'notebook': Notebook,
  'orbit': Orbit,
  'package': Package,
  'paint-roller': PaintRoller,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'palmtree': Palmtree,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  'pen': Pen,
  'pen-tool': PenTool,
  'pencil': Pencil,
  'phone': Phone,
  'phone-call': PhoneCall,
  'piano': Piano,
  'pie-chart': PieChart,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'pin': Pin,
  'pizza': Pizza,
  'plane': Plane,
  'plug': Plug,
  'plug-2': Plug2,
  'presentation': Presentation,
  'printer': Printer,
  'puzzle': Puzzle,
  'rabbit': Rabbit,
  'radio': Radio,
  'receipt': Receipt,
  'recycle': Recycle,
  'rocket': Rocket,
  'route': Route,
  'ruler': Ruler,
  'sailboat': Sailboat,
  'sandwich': Sandwich,
  'satellite': Satellite,
  'school': School,
  'scissors': Scissors,
  'search': Search,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'share-2': Share2,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'ship': Ship,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shower-head': ShowerHead,
  'signpost': Signpost,
  'siren': Siren,
  'skull': Skull,
  'sliders-horizontal': SlidersHorizontal,
  'smartphone': Smartphone,
  'smile': Smile,
  'snail': Snail,
  'snowflake': Snowflake,
  'sofa': Sofa,
  'soup': Soup,
  'sparkle': Sparkle,
  'sparkles': Sparkles,
  'sprout': Sprout,
  'square': Square,
  'squirrel': Squirrel,
  'star': Star,
  'stethoscope': Stethoscope,
  'sticky-note': StickyNote,
  'store': Store,
  'sun': Sun,
  'syringe': Syringe,
  'tablet': Tablet,
  'tag': Tag,
  'target': Target,
  'telescope': Telescope,
  'tent': Tent,
  'terminal': Terminal,
  'thermometer': Thermometer,
  'thermometer-sun': ThermometerSun,
  'ticket': Ticket,
  'toggle-left': ToggleLeft,
  'traffic-cone': TrafficCone,
  'train-front': TrainFront,
  'tree-pine': TreePine,
  'trees': Trees,
  'trending-up': TrendingUp,
  'triangle': Triangle,
  'trophy': Trophy,
  'truck': Truck,
  'turtle': Turtle,
  'tv': Tv,
  'umbrella': Umbrella,
  'user': User,
  'user-round': UserRound,
  'users': Users,
  'utensils': Utensils,
  'utensils-crossed': UtensilsCrossed,
  'video': Video,
  'wallet': Wallet,
  'wallet-2': Wallet2,
  'warehouse': Warehouse,
  'watch': Watch,
  'waves': Waves,
  'wifi': Wifi,
  'wine': Wine,
  'wrench': Wrench,
  'zap': Zap,
  'app-window': AppWindow,
  'binary': Binary,
  'bot': Bot,
  'braces': Braces,
  'check-square': CheckSquare,
  'circuit-board': CircuitBoard,
  'file-code': FileCode,
  'gauge': Gauge,
  'hard-drive': HardDrive,
  'kanban': Kanban,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'list-todo': ListTodo,
  'mouse-pointer': MousePointer2,
  'network': Network,
  'panels-top-left': PanelsTopLeft,
  'router': Router,
  'award': Award,
  'calendar-heart': CalendarHeart,
  'candy': Candy,
  'chef-hat': ChefHat,
  'clipboard-list': ClipboardList,
  'contact': Contact,
  'factory': Factory,
  'file-signature': FileSignature,
  'gavel': Gavel,
  'id-card': IdCard,
  'martini': Martini,
  'paint-bucket': PaintBucket,
  'person-standing': PersonStanding,
  'podcast': Podcast,
  'popcorn': Popcorn,
  'refrigerator': Refrigerator,
  'salad': Salad,
  'scale': Scale,
  'shopping-basket': ShoppingBasket,
  'signature': Signature,
  'speaker': Speaker,
  'spray-can': SprayCan,
  'swords': Swords,
  'users-2': Users2,
  'vault': Vault,
  'volleyball': Volleyball,
  'vote': Vote,
  'washing-machine': WashingMachine,
};

export const PROJECT_ICON_IDS = Object.keys(PROJECT_ICONS);

/**
 * Extra words that find an icon, for the word somebody actually reaches for
 * when it isn't the icon's own name — "desktop" for the monitor, "website"
 * for the globe, "board" for the kanban. The catalog above is named after
 * what each icon draws; this is named after what a project is about.
 */
export const PROJECT_ICON_SYNONYMS: Record<string, string[]> = {
  monitor: ['desktop', 'computer', 'screen', 'display'],
  laptop: ['computer', 'macbook', 'notebook'],
  'app-window': ['desktop', 'application', 'app', 'window'],
  'hard-drive': ['computer', 'storage', 'disk'],
  globe: ['website', 'web', 'internet', 'world', 'site'],
  code: ['dev', 'developer', 'programming', 'coding'],
  'file-code': ['code', 'script', 'dev'],
  braces: ['code', 'json', 'dev', 'api'],
  terminal: ['cli', 'console', 'shell', 'code'],
  server: ['backend', 'hosting', 'cloud'],
  database: ['db', 'sql', 'data'],
  smartphone: ['mobile', 'phone', 'app'],
  cpu: ['processor', 'chip', 'hardware'],
  kanban: ['board', 'scrum', 'agile'],
  'layout-grid': ['board', 'dashboard', 'grid'],
  'layout-dashboard': ['dashboard', 'board', 'admin'],
  'panels-top-left': ['dashboard', 'layout'],
  'list-todo': ['tasks', 'checklist', 'todo'],
  'check-square': ['task', 'done', 'checklist'],
  bot: ['ai', 'robot', 'assistant'],
  router: ['network', 'wifi', 'internet'],
  network: ['connection', 'nodes', 'api'],
  'circuit-board': ['tech', 'electronics', 'hardware'],
  gauge: ['dashboard', 'speed', 'performance', 'metrics'],
  'mouse-pointer': ['cursor', 'click'],
  user: ['person', 'people', 'profile', 'account'],
  'user-round': ['person', 'people', 'profile'],
  'person-standing': ['person', 'people'],
  users: ['people', 'team', 'group', 'friends'],
  'users-2': ['people', 'team', 'community'],
  contact: ['people', 'address book', 'crm'],
  'id-card': ['id', 'identity', 'passport', 'documents'],
  'file-signature': ['contract', 'signature', 'legal', 'documents', 'agreement'],
  signature: ['contract', 'sign'],
  scale: ['legal', 'law', 'justice'],
  gavel: ['legal', 'law', 'court'],
  vault: ['savings', 'bank', 'security', 'finance'],
  'calendar-heart': ['wedding', 'anniversary', 'date', 'love'],
  heart: ['wedding', 'love', 'romance', 'relationship'],
  'party-popper': ['birthday', 'celebration', 'event'],
  'washing-machine': ['laundry', 'chores', 'cleaning'],
  refrigerator: ['fridge', 'kitchen', 'appliance'],
  'spray-can': ['cleaning', 'chores'],
  'paint-bucket': ['renovation', 'diy', 'paint'],
  'chef-hat': ['cooking', 'chef', 'kitchen', 'recipe'],
  salad: ['nutrition', 'diet', 'healthy', 'food'],
  martini: ['drinks', 'bar', 'nightlife', 'cocktail'],
  popcorn: ['movie', 'cinema', 'entertainment'],
  podcast: ['audio', 'show'],
  speaker: ['audio', 'music', 'sound'],
  factory: ['industry', 'manufacturing', 'work'],
  'shopping-basket': ['groceries', 'shopping', 'market'],
  candy: ['kids', 'sweets', 'treats'],
  volleyball: ['sports', 'team sport'],
  award: ['achievement', 'recognition', 'trophy'],
  swords: ['gaming', 'battle', 'fight'],
  'clipboard-list': ['tasks', 'checklist', 'planning'],
  vote: ['election', 'civic', 'community', 'politics'],
};
